// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
  agent any

  options {
    skipStagesAfterUnstable()
  }

  stages {
    stage('Build') {
      steps {
        bat 'mvn -B -DskipTests clean package'
      }
    }

    stage('Test') {
      steps {
        bat 'mvn test'
      }
      post {
        always {
          // Update this glob to wherever your test XMLs are actually written
          junit 'target\\**\\*.xml'
        }
      }
    }

    stage('Deliver') {
      steps {
        bat 'jenkins\\scripts\\delivery.bat'
      }
    }
  }
}
