// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
  agent any

  parameters {
    string(name: 'PASS_THRESHOLD', defaultValue: '90', description: 'Minimum pass % required')
  }

  environment {
    METRICS_FILE = "test-metrics.properties"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build & Test') {
      steps {
        // Keep pipeline running so we can still publish results & compute pass%
        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
          sh 'mvn -B -U test'
        }
      }
    }

    stage('Compute Pass %') {
      steps {
        script {
          // Publish JUnit so Jenkins creates TestResultAction
          junit testResults: 'target/**/*.xml', allowEmptyResults: false, keepLongStdio: true

          def action = currentBuild.rawBuild.getAction(hudson.tasks.junit.TestResultAction)
          def total  = action?.totalCount ?: 0
          def failed = action?.failCount  ?: 0
          def skipped = action?.skipCount ?: 0
          def passed = Math.max(total - failed - skipped, 0)

          def passPct = (total > 0) ? ((passed * 100.0) / total) : 0.0
          def threshold = params.PASS_THRESHOLD as Double

          // Expose for later stages/tools
          env.TEST_TOTAL = "${total}"
          env.TEST_PASSED = "${passed}"
          env.TEST_FAILED = "${failed}"
          env.TEST_SKIPPED = "${skipped}"
          env.TEST_PASS_PCT = String.format('%.2f', passPct)

          currentBuild.description = "Pass%=${env.TEST_PASS_PCT} (P:${passed}/T:${total})"

          writeFile file: env.METRICS_FILE, text: """\
TEST_TOTAL=${total}
TEST_PASSED=${passed}
TEST_FAILED=${failed}
TEST_SKIPPED=${skipped}
TEST_PASS_PCT=${env.TEST_PASS_PCT}
PASS_THRESHOLD=${threshold}
""".stripIndent()

          archiveArtifacts artifacts: env.METRICS_FILE, fingerprint: true

          if (passPct < threshold) {
            error("Pass% ${env.TEST_PASS_PCT} is below threshold ${threshold}.")
          }
        }
      }
    }

    stage('Trigger Revert/Rollback (optional)') {
      when { expression { return currentBuild.currentResult == 'FAILURE' } }
      steps {
        script {
          // Option A (recommended): trigger a rollback job/tool instead of git-reverting automatically
          // build job: 'Rollback-Deploy',
          //   parameters: [
          //     string(name: 'PASS_PCT', value: env.TEST_PASS_PCT),
          //     string(name: 'BUILD_URL', value: env.BUILD_URL)
          //   ],
          //   wait: false

          echo "Rollback/revert step goes here (see options below)."
        }
      }
    }
  }
}
